/*
 * ur5.h:
 * This file has been autogenerated by IR-GEN tool
 * (2018, KU Leuven, Belgium)
 * 
 * License: BSD 2-clause
 */
#ifndef _ILK_GEN_UR5_H_
#define _ILK_GEN_UR5_H_

#include <ilk/eigen/core-types.h>
#include <ilk/eigen/joint-transforms.h>
#include <ilk/eigen/ik.h>
#include "robot-defs.h"

namespace ur5 {
struct mc_config {
	mc_config();

	kul::pose_t camera__fr_link2;
	kul::pose_t fr_link1__fr_jB;
	kul::pose_t fr_link2__fr_jC;
	kul::pose_t fr_link3__fr_jD;
};

void fk1(const ur5::mc_config& mc, const ur5::joint_state& input, kul::pose_t& fr_link1__fr_link3, kul::pose_t& fr_jA__fr_link4, kul::pose_t& fr_jA__fr_jC);
}

#endif //! _ILK_GEN_UR5_H_
  
